services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: "%kernel.project_dir%"
            $qpdfConfig: "%contao_pdf_metadata.qpdf%"
            $exiftoolConfig: "%contao_pdf_metadata.exiftool%"
            $cleanupOnUpload: "%contao_pdf_metadata.cleanup_on_upload%"
            $metadata: "%contao_pdf_metadata.metadata%"

    Postyou\ContaoPdfMetadata\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection}
